# Generated by Django 5.0.3 on 2024-03-17 21:28

import datetime
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("firstname", models.CharField(max_length=20)),
                ("lastname", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("F", "Female"), ("M", "Male")], max_length=1
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region="IR", unique=True
                    ),
                ),
                ("is_email_verified", models.BooleanField(default=False)),
                (
                    "verification_code",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                ("verification_tries_count", models.IntegerField(default=0)),
                (
                    "last_verification_sent",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(2024, 3, 18, 0, 58, 5, 405953),
                        null=True,
                    ),
                ),
                ("has_verification_tries_reset", models.BooleanField(default=False)),
            ],
            options={"abstract": False,},
        ),
    ]
