# Generated by Django 5.0.3 on 2024-03-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("firstname", models.CharField(max_length=20)),
                ("lastname", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("datee", models.DateField()),
                ("date_of_birth", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
                (
                    "gender",
                    models.CharField(
                        choices=[("F", "Female"), ("M", "Male")], max_length=1
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
