# Generated by Django 5.0.3 on 2024-06-05 05:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("firstname", models.CharField(blank=True, max_length=20, null=True)),
                ("lastname", models.CharField(blank=True, max_length=30, null=True)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("F", "Female"), ("M", "Male"), ("B", "Both")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be in a valid Iranian format.",
                                regex="^(?:\\+98|0)(?:\\s?)9[0-9]{9}$",
                            )
                        ],
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("doctor", "Doctor"),
                            ("admin", "Admin"),
                        ],
                        default="user",
                        max_length=255,
                    ),
                ),
                ("is_email_verified", models.BooleanField(default=False)),
                (
                    "verification_code",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                ("verification_tries_count", models.IntegerField(default=0)),
                ("has_verification_tries_reset", models.BooleanField(default=False)),
            ],
            options={"abstract": False,},
        ),
    ]
