# Generated by Django 5.0.3 on 2024-04-26 22:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_verification_sent",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2024, 4, 27, 1, 57, 20, 898014),
                null=True,
            ),
        ),
    ]
