# Generated by Django 5.0.3 on 2024-03-15 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_user_datee"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_verification_tries_reset",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="last_verification_sent",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2024, 3, 15, 14, 0, 36, 7496),
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_code",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_tries_count",
            field=models.IntegerField(default=0),
        ),
    ]
