# Generated by Django 5.0.3 on 2024-04-09 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_last_verification_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_verification_sent",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2024, 4, 9, 9, 49, 59, 946301),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("doctor", "Doctor"), ("admin", "Admin")],
                default="user",
                max_length=255,
            ),
        ),
    ]
