# Generated by Django 5.0.3 on 2024-03-17 22:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_last_verification_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user", name="email", field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_verification_sent",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2024, 3, 18, 1, 49, 49, 351782),
                null=True,
            ),
        ),
    ]
