# Generated by Django 5.0.3 on 2024-03-26 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_last_verification_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="firstname",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("F", "Female"), ("M", "Male"), ("B", "Both")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_verification_sent",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2024, 3, 26, 17, 44, 8, 963102),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="lastname",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
