<<<<<<< HEAD
# Generated by Django 5.0.3 on 2024-04-16 02:05
=======
<<<<<<<< HEAD:BackEnd/accounts/migrations/0005_alter_user_last_verification_sent.py
# Generated by Django 5.0.3 on 2024-04-16 02:22
========
# Generated by Django 5.0.3 on 2024-04-19 08:49
>>>>>>>> dev:BackEnd/accounts/migrations/0003_alter_user_last_verification_sent.py
>>>>>>> dev

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_last_verification_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_verification_sent",
            field=models.DateTimeField(
                blank=True,
<<<<<<< HEAD
                default=datetime.datetime(2024, 4, 16, 5, 35, 38, 697110),
=======
<<<<<<<< HEAD:BackEnd/accounts/migrations/0005_alter_user_last_verification_sent.py
                default=datetime.datetime(2024, 4, 16, 5, 52, 27, 638776),
========
                default=datetime.datetime(2024, 4, 19, 12, 19, 51, 747477),
>>>>>>>> dev:BackEnd/accounts/migrations/0003_alter_user_last_verification_sent.py
>>>>>>> dev
                null=True,
            ),
        ),
    ]
