# Generated by Django 5.0.3 on 2024-04-26 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_last_verification_sent_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_verification_sent",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2024, 4, 26, 12, 57, 19, 267949),
                null=True,
            ),
        ),
    ]
