# Generated by Django 5.0.3 on 2024-03-28 19:55

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_date_of_birth_alter_user_firstname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_verification_sent",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2024, 3, 28, 23, 25, 2, 58513),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be in a valid Iranian format.",
                        regex="^(?:\\+98|0)(?:\\s?)9[0-9]{9}$",
                    )
                ],
            ),
        ),
    ]
