# Generated by Django 5.0.3 on 2024-04-19 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_last_verification_sent_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_verification_sent',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 19, 16, 5, 27, 891800), null=True),
        ),
    ]
