# Generated by Django 5.0.3 on 2024-03-18 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_email_alter_user_last_verification_sent"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="phone_number",),
        migrations.AlterField(
            model_name="user",
            name="last_verification_sent",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2024, 3, 18, 23, 40, 51, 299155),
                null=True,
            ),
        ),
    ]
