# Generated by Django 5.0.3 on 2024-05-02 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_user_last_verification_sent"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="last_verification_sent",),
    ]
