# Generated by Django 5.0.3 on 2024-05-01 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_last_verification_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_verification_sent',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 1, 17, 27, 25, 911772), null=True),
        ),
    ]
