# Generated by Django 5.0.3 on 2024-05-01 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_last_verification_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_verification_sent',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 1, 18, 13, 56, 571669), null=True),
        ),
    ]
