# Generated by Django 5.0.3 on 2024-03-19 03:45

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_user_last_verification_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be in a valid Iranian format.",
                        regex="^\\+?98[09]\\d{9}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_verification_sent",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2024, 3, 19, 7, 15, 53, 124594),
                null=True,
            ),
        ),
    ]
