# Generated by Django 5.0.3 on 2024-03-19 04:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_alter_user_last_verification_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_verification_sent",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2024, 3, 19, 8, 29, 2, 889074),
                null=True,
            ),
        ),
    ]
