# Generated by Django 5.0.3 on 2024-03-21 22:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_alter_user_last_verification_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_verification_sent",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2024, 3, 22, 2, 20, 17, 133087),
                null=True,
            ),
        ),
    ]
