# Generated by Django 5.0.3 on 2024-03-26 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_user_last_verification_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_verification_sent',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 26, 17, 47, 44, 89992), null=True),
        ),
    ]
