# Generated by Django 5.0.3 on 2024-04-02 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_user_last_verification_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_verification_sent',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 2, 10, 55, 41, 864832), null=True),
        ),
    ]
