BEGIN;
--
-- Create model User
--
CREATE TABLE "accounts_user" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "password" varchar(128) NOT NULL, "last_login" timestamp with time zone NULL, "firstname" varchar(20) NULL, "lastname" varchar(30) NULL, "email" varchar(255) NOT NULL UNIQUE, "date_of_birth" date NULL, "gender" varchar(1) NULL, "is_active" boolean NOT NULL, "is_admin" boolean NOT NULL, "phone_number" varchar(15) NULL, "role" varchar(255) NOT NULL, "is_email_verified" boolean NOT NULL, "verification_code" varchar(4) NULL, "verification_tries_count" integer NOT NULL, "has_verification_tries_reset" boolean NOT NULL);
CREATE INDEX "accounts_user_email_b2644a56_like" ON "accounts_user" ("email" varchar_pattern_ops);
COMMIT;
BEGIN;
--
-- Create model Pationt
--
CREATE TABLE "counseling_pationt" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "telegramAccount_id" bigint NULL UNIQUE, "user_id" bigint NOT NULL UNIQUE);
--
-- Create model Psychiatrist
--
CREATE TABLE "counseling_psychiatrist" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "image" varchar(100) NULL, "field" varchar(255) NOT NULL, "telegramAccount_id" bigint NULL UNIQUE, "user_id" bigint NOT NULL UNIQUE);
ALTER TABLE "counseling_pationt" ADD CONSTRAINT "counseling_pationt_telegramAccount_id_623d97a1_fk_telegramb" FOREIGN KEY ("telegramAccount_id") REFERENCES "telegrambot_telegramaccount" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "counseling_pationt" ADD CONSTRAINT "counseling_pationt_user_id_6bd73f45_fk_accounts_user_id" FOREIGN KEY ("user_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "counseling_psychiatrist" ADD CONSTRAINT "counseling_psychiatr_telegramAccount_id_fbbf65f8_fk_telegramb" FOREIGN KEY ("telegramAccount_id") REFERENCES "telegrambot_telegramaccount" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "counseling_psychiatrist" ADD CONSTRAINT "counseling_psychiatrist_user_id_5af83ad6_fk_accounts_user_id" FOREIGN KEY ("user_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
COMMIT;
BEGIN;
--
-- Create model Profile
--
CREATE TABLE "Profile_profile" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "description" text NULL, "name" varchar(50) NULL, "image" varchar(100) NOT NULL, "profile_type" varchar(10) NOT NULL, "created_at" timestamp with time zone NOT NULL, "is_private" boolean NOT NULL, "psychiatrist_id" bigint NOT NULL UNIQUE);
ALTER TABLE "Profile_profile" ADD CONSTRAINT "Profile_profile_psychiatrist_id_0e8ba2a0_fk_counselin" FOREIGN KEY ("psychiatrist_id") REFERENCES "counseling_psychiatrist" ("id") DEFERRABLE INITIALLY DEFERRED;
COMMIT;
BEGIN;
--
-- Create model Reservation
--
CREATE TABLE "reservation_reservation" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "date" date NOT NULL, "time" time NOT NULL, "MeetingLink" varchar(100) NULL, "type" varchar(15) NOT NULL, "day" varchar(10) NOT NULL, "pationt_id" bigint NOT NULL, "psychiatrist_id" bigint NOT NULL);
ALTER TABLE "reservation_reservation" ADD CONSTRAINT "reservation_reservation_date_time_pationt_id_psy_9bef5bc8_uniq" UNIQUE ("date", "time", "pationt_id", "psychiatrist_id");
ALTER TABLE "reservation_reservation" ADD CONSTRAINT "reservation_reservat_pationt_id_c5d4f07f_fk_counselin" FOREIGN KEY ("pationt_id") REFERENCES "counseling_pationt" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "reservation_reservation" ADD CONSTRAINT "reservation_reservat_psychiatrist_id_2de317b0_fk_counselin" FOREIGN KEY ("psychiatrist_id") REFERENCES "counseling_psychiatrist" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "reservation_reservation_pationt_id_c5d4f07f" ON "reservation_reservation" ("pationt_id");
CREATE INDEX "reservation_reservation_psychiatrist_id_2de317b0" ON "reservation_reservation" ("psychiatrist_id");
COMMIT;
BEGIN;
--
-- Create model GlasserTest
--
CREATE TABLE "TherapyTests_glassertest" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "love" double precision NOT NULL, "survive" double precision NOT NULL, "freedom" double precision NOT NULL, "power" double precision NOT NULL, "fun" double precision NOT NULL);
--
-- Create model TreatementHistory
--
CREATE TABLE "TherapyTests_treatementhistory" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "end_date" date NOT NULL, "length" integer NOT NULL, "is_finished" boolean NOT NULL, "reason_to_leave" text NOT NULL, "approach" text NULL, "special_drugs" text NOT NULL);
--
-- Create model MedicalRecordPermission
--
CREATE TABLE "TherapyTests_medicalrecordpermission" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_date" date NOT NULL, "pationt_id" bigint NOT NULL, "psychiatrist_id" bigint NOT NULL);
--
-- Create model Permission
--
CREATE TABLE "TherapyTests_permission" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_date" date NOT NULL, "pationt_id" bigint NOT NULL, "psychiatrist_id" bigint NOT NULL);
--
-- Create model TherapyTests
--
CREATE TABLE "TherapyTests_therapytests" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "MBTItest" varchar(6) NULL, "glasserTest_id" bigint NULL, "pationt_id" bigint NOT NULL UNIQUE);
--
-- Create model MedicalRecord
--
CREATE TABLE "TherapyTests_medicalrecord" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "child_num" integer NOT NULL, "name" varchar(50) NULL, "created_at" timestamp with time zone NOT NULL, "age" integer NOT NULL, "gender" varchar(5) NULL, "family_history" boolean NOT NULL, "nationalID" varchar(10) NOT NULL, "pationt_id" bigint NOT NULL UNIQUE, "therapyTests_id" bigint NULL UNIQUE, "treatementHistory1_id" bigint NULL, "treatementHistory2_id" bigint NULL, "treatementHistory3_id" bigint NULL);
ALTER TABLE "TherapyTests_medicalrecordpermission" ADD CONSTRAINT "TherapyTests_medical_pationt_id_70b22c23_fk_counselin" FOREIGN KEY ("pationt_id") REFERENCES "counseling_pationt" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "TherapyTests_medicalrecordpermission" ADD CONSTRAINT "TherapyTests_medical_psychiatrist_id_ce385923_fk_counselin" FOREIGN KEY ("psychiatrist_id") REFERENCES "counseling_psychiatrist" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "TherapyTests_medicalrecordpermission_pationt_id_70b22c23" ON "TherapyTests_medicalrecordpermission" ("pationt_id");
CREATE INDEX "TherapyTests_medicalrecordpermission_psychiatrist_id_ce385923" ON "TherapyTests_medicalrecordpermission" ("psychiatrist_id");
ALTER TABLE "TherapyTests_permission" ADD CONSTRAINT "TherapyTests_permiss_pationt_id_d7694a38_fk_counselin" FOREIGN KEY ("pationt_id") REFERENCES "counseling_pationt" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "TherapyTests_permission" ADD CONSTRAINT "TherapyTests_permiss_psychiatrist_id_fb7952ef_fk_counselin" FOREIGN KEY ("psychiatrist_id") REFERENCES "counseling_psychiatrist" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "TherapyTests_permission_pationt_id_d7694a38" ON "TherapyTests_permission" ("pationt_id");
CREATE INDEX "TherapyTests_permission_psychiatrist_id_fb7952ef" ON "TherapyTests_permission" ("psychiatrist_id");
ALTER TABLE "TherapyTests_therapytests" ADD CONSTRAINT "TherapyTests_therapy_glasserTest_id_ca0c5e00_fk_TherapyTe" FOREIGN KEY ("glasserTest_id") REFERENCES "TherapyTests_glassertest" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "TherapyTests_therapytests" ADD CONSTRAINT "TherapyTests_therapy_pationt_id_b4d94492_fk_counselin" FOREIGN KEY ("pationt_id") REFERENCES "counseling_pationt" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "TherapyTests_therapytests_glasserTest_id_ca0c5e00" ON "TherapyTests_therapytests" ("glasserTest_id");
ALTER TABLE "TherapyTests_medicalrecord" ADD CONSTRAINT "TherapyTests_medical_pationt_id_1ce577a4_fk_counselin" FOREIGN KEY ("pationt_id") REFERENCES "counseling_pationt" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "TherapyTests_medicalrecord" ADD CONSTRAINT "TherapyTests_medical_therapyTests_id_a65047ad_fk_TherapyTe" FOREIGN KEY ("therapyTests_id") REFERENCES "TherapyTests_therapytests" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "TherapyTests_medicalrecord" ADD CONSTRAINT "TherapyTests_medical_treatementHistory1_i_69da1514_fk_TherapyTe" FOREIGN KEY ("treatementHistory1_id") REFERENCES "TherapyTests_treatementhistory" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "TherapyTests_medicalrecord" ADD CONSTRAINT "TherapyTests_medical_treatementHistory2_i_31d0b597_fk_TherapyTe" FOREIGN KEY ("treatementHistory2_id") REFERENCES "TherapyTests_treatementhistory" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "TherapyTests_medicalrecord" ADD CONSTRAINT "TherapyTests_medical_treatementHistory3_i_61d71d99_fk_TherapyTe" FOREIGN KEY ("treatementHistory3_id") REFERENCES "TherapyTests_treatementhistory" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "TherapyTests_medicalrecord_treatementHistory1_id_69da1514" ON "TherapyTests_medicalrecord" ("treatementHistory1_id");
CREATE INDEX "TherapyTests_medicalrecord_treatementHistory2_id_31d0b597" ON "TherapyTests_medicalrecord" ("treatementHistory2_id");
CREATE INDEX "TherapyTests_medicalrecord_treatementHistory3_id_61d71d99" ON "TherapyTests_medicalrecord" ("treatementHistory3_id");
COMMIT;
BEGIN;
--
-- Create model TelegramAccount
--
CREATE TABLE "telegrambot_telegramaccount" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "is_varify" boolean NOT NULL, "chat_id" varchar(15) NOT NULL UNIQUE, "varification_code" varchar(4) NULL);
CREATE INDEX "telegrambot_telegramaccount_chat_id_90317474_like" ON "telegrambot_telegramaccount" ("chat_id" varchar_pattern_ops);
COMMIT;
BEGIN;
--
-- Create model Rating
--
CREATE TABLE "Rating_rating" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "rating" integer NOT NULL CHECK ("rating" >= 0), "comments" text NOT NULL, "pationt_id" bigint NOT NULL, "psychiatrist_id" bigint NOT NULL);
ALTER TABLE "Rating_rating" ADD CONSTRAINT "Rating_rating_psychiatrist_id_pationt_id_a9213f01_uniq" UNIQUE ("psychiatrist_id", "pationt_id");
ALTER TABLE "Rating_rating" ADD CONSTRAINT "Rating_rating_pationt_id_c5de5659_fk_counseling_pationt_id" FOREIGN KEY ("pationt_id") REFERENCES "counseling_pationt" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "Rating_rating" ADD CONSTRAINT "Rating_rating_psychiatrist_id_45a8a844_fk_counselin" FOREIGN KEY ("psychiatrist_id") REFERENCES "counseling_psychiatrist" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "Rating_rating_pationt_id_c5de5659" ON "Rating_rating" ("pationt_id");
CREATE INDEX "Rating_rating_psychiatrist_id_45a8a844" ON "Rating_rating" ("psychiatrist_id");
COMMIT;
BEGIN;
--
-- Create model DoctorPanel
--
CREATE TABLE "Doctorpanel_doctorpanel" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "date" date NULL, "time" time NULL, "psychiatrist_id" bigint NOT NULL);
ALTER TABLE "Doctorpanel_doctorpanel" ADD CONSTRAINT "Doctorpanel_doctorpa_psychiatrist_id_39dae76f_fk_counselin" FOREIGN KEY ("psychiatrist_id") REFERENCES "counseling_psychiatrist" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "Doctorpanel_doctorpanel_psychiatrist_id_39dae76f" ON "Doctorpanel_doctorpanel" ("psychiatrist_id");
COMMIT;
