version: "3.9"

services:
  db:
    restart: always
    container_name: postgreSQL
    image: postgres:13.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - shared_data:/app/data/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Hgbr5391
      - POSTGRES_DB=TherapyDB
    ports:
      - '5432:5432'
    networks:
      - eniac

  backend:
    build: .
    container_name: backend
    volumes:
      - .:/app
      - media_volume:/app/media
      - shared_data:/app/data/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Hgbr5391
      - POSTGRES_DB=TherapyDB
    depends_on:
      - db
    command: ./docker-entrypoint.sh
    ports:
      - '8000:8000'
    expose:
      - '8000' 
    networks:
      - eniac

networks:
  eniac:
    driver: bridge

volumes:
  postgres_data:
  media_volume:
  shared_data:

  # nginx:
  #   image: nginx
  #   container_name: nginx
  #   restart: always
  #   ports:
  #     - "8070:80"
  #   volumes:
  #     - ./deployment/nginx_default.conf:/etc/nginx/conf.d/default.conf
  #     # - static_volume:/home/app/static
  #     - media_volume:/home/app/media
  #   depends_on:
  #     - backend
  #   networks:
  #     - eniac

  

  # deploy:
    #   resources:
    #     limits:
    #       memory: 4G
    #     reservations:
    #       memory: 4G
  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #   entrypoint: |
  #     /bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $$!; done;'
  #   networks:
  #     - eniac



    # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - ./telegrambot.crt:/etc/nginx/telegrambot.crt
  #     - ./telegrambot.key:/etc/nginx/telegrambot.key
  #     - media_volume:/home/app/media
  #     - shared_data:/app/data/
  #     - ./certbot/fullchain.pem:/etc/letsencrypt/live/sinaharaeeni.ir/fullchain.pem:ro
  #     - ./certbot/privkey.pem:/etc/letsencrypt/live/sinaharaeeni.ir/privkey.pem:ro
  #   ports:
  #     - '9080:80'
  #     - '8443:443'
  #   depends_on:
  #     - backend
  #   networks:
  #     - eniac

