FROM ubuntu:22.04

RUN apt-get update && apt-get install -y python3 python3-pip python3-venv supervisor build-essential python3-dev libpq-dev

# ARG USER=root
RUN groupadd app && useradd -g app app

USER $USER

RUN python3 -m venv eniac_venv

WORKDIR /app

# install dependencies
COPY requirements.txt /app/
RUN /eniac_venv/bin/pip install -r requirements.txt

ENV VIRTUAL_ENV=/eniac_venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# Copy project
COPY . /app/

EXPOSE 8000


CMD [ "python" , "manage.py" , "runserver" ]