BEGIN;
--
-- Create model GlasserTest
--
CREATE TABLE "TherapyTests_glassertest" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "love" double precision NOT NULL, "survive" double precision NOT NULL, "freedom" double precision NOT NULL, "power" double precision NOT NULL, "fun" double precision NOT NULL);
--
-- Create model TreatementHistory
--
CREATE TABLE "TherapyTests_treatementhistory" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "end_date" date NOT NULL, "length" integer NOT NULL, "is_finished" boolean NOT NULL, "reason_to_leave" text NOT NULL, "approach" text NULL, "special_drugs" text NOT NULL);
--
-- Create model MedicalRecordPermission
--
CREATE TABLE "TherapyTests_medicalrecordpermission" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_date" date NOT NULL, "pationt_id" bigint NOT NULL, "psychiatrist_id" bigint NOT NULL);
--
-- Create model TherapyTests
--
CREATE TABLE "TherapyTests_therapytests" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "MBTItest" varchar(6) NULL, "glasserTest_id" bigint NULL, "pationt_id" bigint NOT NULL UNIQUE);
--
-- Create model MedicalRecord
--
CREATE TABLE "TherapyTests_medicalrecord" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "child_num" integer NOT NULL, "name" varchar(50) NULL, "created_at" timestamp with time zone NOT NULL, "age" integer NOT NULL, "gender" varchar(5) NULL, "family_history" boolean NOT NULL, "nationalID" varchar(10) NOT NULL, "pationt_id" bigint NOT NULL UNIQUE, "therapyTests_id" bigint NULL UNIQUE, "treatementHistory1_id" bigint NULL, "treatementHistory2_id" bigint NULL, "treatementHistory3_id" bigint NULL);
ALTER TABLE "TherapyTests_medicalrecordpermission" ADD CONSTRAINT "TherapyTests_medical_pationt_id_70b22c23_fk_counselin" FOREIGN KEY ("pationt_id") REFERENCES "counseling_pationt" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "TherapyTests_medicalrecordpermission" ADD CONSTRAINT "TherapyTests_medical_psychiatrist_id_ce385923_fk_counselin" FOREIGN KEY ("psychiatrist_id") REFERENCES "counseling_psychiatrist" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "TherapyTests_medicalrecordpermission_pationt_id_70b22c23" ON "TherapyTests_medicalrecordpermission" ("pationt_id");
CREATE INDEX "TherapyTests_medicalrecordpermission_psychiatrist_id_ce385923" ON "TherapyTests_medicalrecordpermission" ("psychiatrist_id");
ALTER TABLE "TherapyTests_therapytests" ADD CONSTRAINT "TherapyTests_therapy_glasserTest_id_ca0c5e00_fk_TherapyTe" FOREIGN KEY ("glasserTest_id") REFERENCES "TherapyTests_glassertest" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "TherapyTests_therapytests" ADD CONSTRAINT "TherapyTests_therapy_pationt_id_b4d94492_fk_counselin" FOREIGN KEY ("pationt_id") REFERENCES "counseling_pationt" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "TherapyTests_therapytests_glasserTest_id_ca0c5e00" ON "TherapyTests_therapytests" ("glasserTest_id");
ALTER TABLE "TherapyTests_medicalrecord" ADD CONSTRAINT "TherapyTests_medical_pationt_id_1ce577a4_fk_counselin" FOREIGN KEY ("pationt_id") REFERENCES "counseling_pationt" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "TherapyTests_medicalrecord" ADD CONSTRAINT "TherapyTests_medical_therapyTests_id_a65047ad_fk_TherapyTe" FOREIGN KEY ("therapyTests_id") REFERENCES "TherapyTests_therapytests" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "TherapyTests_medicalrecord" ADD CONSTRAINT "TherapyTests_medical_treatementHistory1_i_69da1514_fk_TherapyTe" FOREIGN KEY ("treatementHistory1_id") REFERENCES "TherapyTests_treatementhistory" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "TherapyTests_medicalrecord" ADD CONSTRAINT "TherapyTests_medical_treatementHistory2_i_31d0b597_fk_TherapyTe" FOREIGN KEY ("treatementHistory2_id") REFERENCES "TherapyTests_treatementhistory" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "TherapyTests_medicalrecord" ADD CONSTRAINT "TherapyTests_medical_treatementHistory3_i_61d71d99_fk_TherapyTe" FOREIGN KEY ("treatementHistory3_id") REFERENCES "TherapyTests_treatementhistory" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "TherapyTests_medicalrecord_treatementHistory1_id_69da1514" ON "TherapyTests_medicalrecord" ("treatementHistory1_id");
CREATE INDEX "TherapyTests_medicalrecord_treatementHistory2_id_31d0b597" ON "TherapyTests_medicalrecord" ("treatementHistory2_id");
CREATE INDEX "TherapyTests_medicalrecord_treatementHistory3_id_61d71d99" ON "TherapyTests_medicalrecord" ("treatementHistory3_id");
COMMIT;
