# Generated by Django 5.0.3 on 2024-03-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counseling", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="psychiatrist", old_name="type", new_name="field",
        ),
        migrations.AddField(
            model_name="psychiatrist",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="psychiatrist",
            name="image",
            field=models.ImageField(
                default="images/doctors/profile_pics/default.png",
                null=True,
                upload_to="images/doctors/profile_pics",
            ),
        ),
    ]
