# Generated by Django 5.0.3 on 2024-04-14 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counseling", "0001_initial"),
        ("telegrambot", "0002_remove_telegramaccount_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="pationt",
            name="telegramAccount",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="telegrambot.telegramaccount",
            ),
        ),
        migrations.AddField(
            model_name="psychiatrist",
            name="telegramAccount",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="telegrambot.telegramaccount",
            ),
        ),
    ]
