# Generated by Django 5.0.3 on 2024-05-12 14:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychiatrist',
            name='free_times',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), blank=True, default=list, null=True, size=None),
        ),
    ]
