# Generated by Django 5.0.3 on 2024-03-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counseling", "0002_rename_type_psychiatrist_field_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="psychiatrist", name="description",),
        migrations.AlterField(
            model_name="psychiatrist",
            name="field",
            field=models.CharField(
                choices=[
                    ("individual", "Individual"),
                    ("couples", "Couples"),
                    ("kids", "Kids"),
                    ("teen", "Teen"),
                ],
                default="defualt",
                max_length=255,
            ),
        ),
    ]
