# Generated by Django 5.0.3 on 2024-05-14 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0002_psychiatrist_free_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psychiatrist',
            name='free_times',
        ),
    ]
