# Generated by Django 5.0.3 on 2024-04-18 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counseling", "0002_pationt_telegramaccount_psychiatrist_telegramaccount"),
        ("telegrambot", "0002_remove_telegramaccount_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="pationt",
            name="telegramAccount",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="telegrambot.telegramaccount",
            ),
        ),
        migrations.AlterField(
            model_name="pationt",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="psychiatrist",
            name="telegramAccount",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="telegrambot.telegramaccount",
            ),
        ),
    ]
