# Generated by Django 5.0.3 on 2024-04-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counseling", "0002_alter_psychiatrist_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="psychiatrist",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/doctors/profile_pics"
            ),
        ),
    ]
