# Generated by Django 5.0.3 on 2024-04-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counseling", "0003_alter_psychiatrist_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="psychiatrist",
            name="field",
            field=models.CharField(
                choices=[
                    ("individual", "فردی"),
                    ("couples", "زوج"),
                    ("kids", "کودک"),
                    ("teen", "نوجوان"),
                ],
                default="defualt",
                max_length=255,
            ),
        ),
    ]
