# Generated by Django 5.0.3 on 2024-04-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counseling", "0004_alter_psychiatrist_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="psychiatrist",
            name="field",
            field=models.CharField(
                choices=[
                    ("فردی", "فردی"),
                    ("زوج", "زوج"),
                    ("کودک", "کودک"),
                    ("نوجوان", "نوجوان"),
                ],
                default="defualt",
                max_length=255,
            ),
        ),
    ]
