# Generated by Django 5.0.3 on 2024-05-10 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("counseling", "0001_initial"),
        ("reservation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorPanel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "psychiatrist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="counseling.psychiatrist",
                    ),
                ),
                ("reservations", models.ManyToManyField(to="reservation.reservation")),
            ],
        ),
    ]
