# Generated by Django 5.0.3 on 2024-05-14 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctorpanel', '0002_remove_doctorpanel_reservations_doctorpanel_date_and_more'),
        ('counseling', '0003_remove_psychiatrist_free_times'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoctorPanel',
            new_name='FreeTime',
        ),
    ]
