# Generated by Django 5.0.3 on 2024-06-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctorpanel', '0003_rename_doctorpanel_freetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='freetime',
            name='day',
            field=models.CharField(blank=True, choices=[('شنبه', 'شنبه'), ('یکشنبه', 'یک\u200cشنبه'), ('دوشنبه', 'دو\u200cشنبه'), ('سه\u200cشنبه', 'سه\u200cشنبه'), ('چهارشنبه', 'چهار\u200cشنبه'), ('پنج\u200cشنبه', 'پنج\u200cشنبه'), ('جمعه', 'جمعه')], max_length=10),
        ),
        migrations.AddField(
            model_name='freetime',
            name='month',
            field=models.CharField(blank=True, choices=[('فروردین', 'فروردین'), ('اردیبهشت', 'اردیبهشت'), ('خرداد', 'خرداد'), ('تیر', 'تیر'), ('مرداد', 'مرداد'), ('شهریور', 'شهریور'), ('مهر', 'مهر'), ('ابان', 'ابان'), ('اذر', 'اذر'), ('دی', 'دی'), ('بهمن', 'بهمن'), ('اسفند', 'اسفند')], max_length=10),
        ),
    ]
