# Generated by Django 5.0.3 on 2024-04-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="day",
            field=models.CharField(
                blank=True,
                choices=[
                    ("شنبه", "شنبه"),
                    ("یک\u200cشنبه", "یک\u200cشنبه"),
                    ("دو\u200cشنبه", "دو\u200cشنبه"),
                    ("سه\u200cشنبه", "سه\u200cشنبه"),
                    ("چهار\u200cشنبه", "چهار\u200cشنبه"),
                    ("پنج\u200cشنبه", "پنج\u200cشنبه"),
                    ("جمعه", "جمعه"),
                ],
                max_length=10,
            ),
        ),
    ]
