# Generated by Django 5.0.3 on 2024-04-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='MeetingLink',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
