# Generated by Django 5.0.3 on 2024-04-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0002_alter_reservation_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="type",
            field=models.CharField(
                choices=[("حضوری", "حضوری"), ("مجازی", "مجازی")], max_length=15
            ),
        ),
    ]
