# Generated by Django 5.0.3 on 2024-04-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counseling", "0004_alter_psychiatrist_user"),
        ("reservation", "0003_alter_reservation_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reservation",
            unique_together={("date", "time", "pationt", "psychiatrist")},
        ),
        migrations.AlterField(
            model_name="reservation",
            name="day",
            field=models.CharField(
                blank=True,
                choices=[
                    ("شنبه", "شنبه"),
                    ("یکشنبه", "یک\u200cشنبه"),
                    ("دوشنبه", "دو\u200cشنبه"),
                    ("سه\u200cشنبه", "سه\u200cشنبه"),
                    ("چهارشنبه", "چهار\u200cشنبه"),
                    ("پنج\u200cشنبه", "پنج\u200cشنبه"),
                    ("جمعه", "جمعه"),
                ],
                max_length=10,
            ),
        ),
    ]
