# Generated by Django 5.0.3 on 2024-05-01 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rating', '0001_initial'),
        ('counseling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='pationt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counseling.pationt'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='psychiatrist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counseling.psychiatrist'),
        ),
    ]
