# Generated by Django 5.0.3 on 2024-05-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rating', '0002_alter_rating_pationt_alter_rating_psychiatrist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
