# Generated by Django 5.0.3 on 2024-06-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TelegramAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_varify", models.BooleanField(default=False)),
                ("chat_id", models.CharField(max_length=15, unique=True)),
                (
                    "varification_code",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
            ],
        ),
    ]
