# Generated by Django 5.0.3 on 2024-04-11 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("counseling", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TherapyTests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("MBTItest", models.CharField(blank=True, max_length=6)),
                (
                    "pationt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="counseling.pationt",
                    ),
                ),
            ],
        ),
    ]
