# Generated by Django 5.0.3 on 2024-04-19 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("counseling", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlasserTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("love", models.FloatField(default=0.0)),
                ("survive", models.FloatField(default=0.0)),
                ("freedom", models.FloatField(default=0.0)),
                ("power", models.FloatField(default=0.0)),
                ("fun", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="TherapyTests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("MBTItest", models.CharField(blank=True, max_length=6)),
                (
                    "glasserTest",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="TherapyTests.glassertest",
                    ),
                ),
                (
                    "pationt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="counseling.pationt",
                    ),
                ),
            ],
        ),
    ]
