# Generated by Django 5.0.3 on 2024-05-17 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("counseling", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlasserTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("love", models.FloatField(default=0.0)),
                ("survive", models.FloatField(default=0.0)),
                ("freedom", models.FloatField(default=0.0)),
                ("power", models.FloatField(default=0.0)),
                ("fun", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="TreatementHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("end_date", models.DateField()),
                ("length", models.IntegerField()),
                ("is_finished", models.BooleanField(default=True)),
                ("reason_to_leave", models.TextField(blank=True, max_length=500)),
                ("approach", models.TextField(blank=True, max_length=30, null=True)),
                ("special_drugs", models.TextField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="MedicalRecordPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateField()),
                (
                    "pationt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="counseling.pationt",
                    ),
                ),
                (
                    "psychiatrist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="counseling.psychiatrist",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TherapyTests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("MBTItest", models.CharField(blank=True, max_length=6, null=True)),
                (
                    "glasserTest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="TherapyTests.glassertest",
                    ),
                ),
                (
                    "pationt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="counseling.pationt",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("child_num", models.IntegerField()),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("age", models.IntegerField(verbose_name=range(4, 80))),
                (
                    "gender",
                    models.CharField(
                        choices=[("زن", "زن"), ("مرد", "مرد")], max_length=5, null=True
                    ),
                ),
                ("family_history", models.BooleanField(default=False)),
                ("nationalID", models.CharField(max_length=10)),
                (
                    "pationt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="counseling.pationt",
                    ),
                ),
                (
                    "therapyTests",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="TherapyTests.therapytests",
                    ),
                ),
                (
                    "treatementHistory1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="treatement_history1",
                        to="TherapyTests.treatementhistory",
                    ),
                ),
                (
                    "treatementHistory2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="treatement_history2",
                        to="TherapyTests.treatementhistory",
                    ),
                ),
                (
                    "treatementHistory3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="treatement_history3",
                        to="TherapyTests.treatementhistory",
                    ),
                ),
            ],
        ),
    ]
