# Generated by Django 5.0.3 on 2024-05-11 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TherapyTests", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalrecordpermission",
            name="created_date",
            field=models.DateField(default=datetime.date(2024, 5, 11)),
        ),
    ]
