# Generated by Django 5.0.3 on 2024-04-17 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TherapyTests", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlasserTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("love", models.FloatField(default=0.0)),
                ("survive", models.FloatField(default=0.0)),
                ("freedom", models.FloatField(default=0.0)),
                ("power", models.FloatField(default=0.0)),
                ("fun", models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name="therapytests",
            name="glasserTest",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="TherapyTests.glassertest",
            ),
        ),
    ]
