# Generated by Django 5.0.3 on 2024-05-03 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TherapyTests", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalrecord",
            name="treatementHistory1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="treatement_history1",
                to="TherapyTests.treatementhistory",
            ),
        ),
        migrations.AlterField(
            model_name="medicalrecord",
            name="treatementHistory2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="treatement_history2",
                to="TherapyTests.treatementhistory",
            ),
        ),
        migrations.AlterField(
            model_name="medicalrecord",
            name="treatementHistory3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="treatement_history3",
                to="TherapyTests.treatementhistory",
            ),
        ),
    ]
