# Generated by Django 5.0.3 on 2024-05-03 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TherapyTests", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="therapytests",
            name="glasserTest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="TherapyTests.glassertest",
            ),
        ),
    ]
