# Generated by Django 5.0.3 on 2024-05-14 21:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TherapyTests', '0002_delete_permission'),
        ('counseling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=datetime.date(2024, 5, 14))),
                ('pationt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counseling.pationt')),
                ('psychiatrist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counseling.psychiatrist')),
            ],
        ),
    ]
