# Generated by Django 5.0.3 on 2024-05-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TherapyTests", "0002_alter_therapytests_glassertest"),
    ]

    operations = [
        migrations.AddField(
            model_name="therapytests",
            name="somTest",
            field=models.CharField(blank=True, null=True),
        ),
    ]
