# Generated by Django 5.0.3 on 2024-06-01 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TherapyTests', '0002_alter_medicalrecordpermission_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecordpermission',
            name='created_date',
            field=models.DateField(default=datetime.date(2024, 6, 1)),
        ),
    ]
