# Generated by Django 5.0.3 on 2024-04-24 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TherapyTests", "0002_treatementhistory_alter_therapytests_mbtitest_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalrecord",
            name="therapyTests",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="TherapyTests.therapytests",
            ),
        ),
    ]
