# Generated by Django 5.0.3 on 2024-05-03 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TherapyTests", "0003_therapytests_somtest"),
    ]

    operations = [
        migrations.RemoveField(model_name="therapytests", name="somTest",),
    ]
