# Generated by Django 5.0.3 on 2024-05-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TherapyTests', '0003_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='created_date',
            field=models.DateField(),
        ),
    ]
