# Generated by Django 5.0.3 on 2024-05-14 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TherapyTests", "0004_alter_test_created_date"),
        ("counseling", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="test333",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateField()),
                (
                    "pationt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="counseling.pationt",
                    ),
                ),
                (
                    "psychiatrist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="counseling.psychiatrist",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="test",),
    ]
