# Generated by Django 5.0.3 on 2024-05-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TherapyTests", "0004_remove_therapytests_somtest"),
    ]

    operations = [
        migrations.CreateModel(
            name="dangling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("MBTItest", models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
    ]
