# Generated by Django 5.0.3 on 2024-05-03 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TherapyTests", "0005_dangling"),
    ]

    operations = [
        migrations.DeleteModel(name="dangling",),
    ]
