# Generated by Django 5.0.3 on 2024-05-14 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TherapyTests', '0005_test333_delete_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test333',
        ),
    ]
