# Generated by Django 5.0.3 on 2024-03-28 21:00

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("counseling", "0002_rename_type_psychiatrist_field_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PsychiatristProfile",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": [],},
            bases=("counseling.psychiatrist",),
        ),
    ]
