# Generated by Django 5.0.3 on 2024-03-29 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Profile", "0001_initial"),
        ("counseling", "0003_remove_psychiatrist_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "image",
                    models.ImageField(
                        default="images/profile_pics/default.png",
                        upload_to="images/profile_pics",
                    ),
                ),
                ("profile_type", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_private", models.BooleanField(default=False)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="counseling.psychiatrist",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="PsychiatristProfile",),
    ]
