# Generated by Django 5.0.3 on 2024-04-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Profile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(upload_to="images\\doctors\\profile_pics"),
        ),
    ]
