# Generated by Django 5.0.3 on 2024-03-29 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Profile", "0002_doctorprofile_delete_psychiatristprofile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doctorprofile", old_name="doctor", new_name="psychiatrist",
        ),
    ]
