# Generated by Django 5.0.3 on 2024-03-29 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Profile", "0003_rename_doctor_doctorprofile_psychiatrist"),
        ("counseling", "0003_remove_psychiatrist_description_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="DoctorProfile", new_name="Profile",),
    ]
