# Generated by Django 5.0.3 on 2024-03-29 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Profile", "0004_rename_doctorprofile_profile"),
        ("counseling", "0003_remove_psychiatrist_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="psychiatrist",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="counseling.psychiatrist",
            ),
        ),
    ]
